ALTER TABLE "Event" ADD COLUMN "matchingStartsAt" TIMESTAMP(3) NULL DEFAULT NULL;
ALTER TABLE "Event" ADD COLUMN "matchingDueAt" TIMESTAMP(3) NULL DEFAULT NULL;
ALTER TABLE "Event" ADD COLUMN "matchingEndsAt" TIMESTAMP(3) NULL DEFAULT NULL;
ALTER TABLE "Event" ADD COLUMN "projectWorkStartsAt" TIMESTAMP(3) NULL DEFAULT NULL;