ALTER TABLE "Event" ADD COLUMN     "defaultWeeks" INTEGER NOT NULL DEFAULT 4;
ALTER TABLE "Event" ADD COLUMN     "hasBeginner" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Event" ADD COLUMN     "hasIntermediate" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Event" ADD COLUMN     "hasAdvanced" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Student" ADD COLUMN "interviewNotes" TEXT NULL DEFAULT NULL;