CREATE TABLE "Repository" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    "logoUrl" TEXT NULL DEFAULT NULL,
    "name" TEXT NOT NULL,
    "url" TEXT NOT NULL,
	
    PRIMARY KEY ("id")
);

CREATE TABLE "Artifact" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    "name" TEXT NOT NULL,
    "link" TEXT NOT NULL,
	
    "studentId" TEXT NULL DEFAULT NULL,
    "mentorId" TEXT NULL DEFAULT NULL,
    "projectId" TEXT NOT NULL,
    "artifactTypeId" TEXT NULL DEFAULT NULL,
	
    PRIMARY KEY ("id")
);

CREATE TABLE "ArtifactType" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    "name" TEXT NOT NULL,
    "personType" "PersonType" NULL DEFAULT NULL,
    "description" TEXT NOT NULL,
    "required" BOOLEAN NOT NULL DEFAULT FALSE,

    "eventId" TEXT NOT NULL,
	
    PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "ArtifactType" ADD FOREIGN KEY ("eventId") REFERENCES "Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Artifact" ADD FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Artifact" ADD FOREIGN KEY ("mentorId") REFERENCES "Mentor"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Artifact" ADD FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Artifact" ADD FOREIGN KEY ("artifactTypeId") REFERENCES "ArtifactType"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Project" ADD COLUMN "issueUrl" TEXT NULL DEFAULT NULL;
ALTER TABLE "Project" ADD COLUMN "repositoryId" TEXT NULL DEFAULT NULL;
ALTER TABLE "Project" ADD COLUMN "complete" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "Project" ADD FOREIGN KEY ("repositoryId") REFERENCES "Repository"("id") ON DELETE SET NULL ON UPDATE CASCADE;