ALTER TABLE "Event" ADD COLUMN "isActive" BOOLEAN DEFAULT false;
ALTER TABLE "Event" ADD COLUMN "slackWorkspaceId" TEXT NULL DEFAULT NULL;
ALTER TABLE "Event" ADD COLUMN "slackUserGroupId" TEXT NULL DEFAULT NULL;
ALTER TABLE "Event" ADD COLUMN "slackWorkspaceAccessToken" TEXT NULL DEFAULT NULL;
ALTER TABLE "Event" ADD COLUMN "standupAndProsperToken" TEXT NULL DEFAULT NULL;

ALTER TABLE "Student" ADD COLUMN "slackId" TEXT NULL DEFAULT NULL;

ALTER TABLE "Project" ADD COLUMN "slackChannelId" TEXT NULL DEFAULT NULL;
ALTER TABLE "Project" ADD COLUMN "standupId" TEXT NULL DEFAULT NULL;

CREATE TABLE "StandupResult" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "eventId" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,

    "threadDueAt" TIMESTAMP(3) NOT NULL,
    "threadId" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "rating" INT NULL DEFAULT NULL,
    "humanRated" BOOLEAN NOT NULL DEFAULT FALSE,

    PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "StandupResult" ADD FOREIGN KEY ("eventId") REFERENCES "Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StandupResult" ADD FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StandupResult" ADD FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;