CREATE TABLE "ProjectEmail" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    "subject" TEXT NULL DEFAULT NULL,
    "to" TEXT NULL DEFAULT NULL,
    "cc" TEXT NULL DEFAULT NULL,
    "textBody" TEXT NULL DEFAULT NULL,
    "htmlBody" TEXT NULL DEFAULT NULL,

    "studentId" TEXT NULL DEFAULT NULL,
    "mentorId" TEXT NULL DEFAULT NULL,
    "projectId" TEXT NOT NULL,
	
    PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "ProjectEmail" ADD FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProjectEmail" ADD FOREIGN KEY ("mentorId") REFERENCES "Mentor"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProjectEmail" ADD FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Event" ADD COLUMN "emailSignature" TEXT NULL DEFAULT NULL;